name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
          git restore .

      - name: Setup prettier cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/prettier
          key: prettier-${{ github.sha }}
          restore-keys: |
            prettier-

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format"
